// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvagvwrpdcxqqqdupvqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2YWd2d3JwZGN4cXFxZHVwdnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjY2NTEsImV4cCI6MjA2MjY0MjY1MX0.HjmbGZvfDxNSNqPsVzTQPOWrlPwtdqy8o-0hZeJqE5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);